unbind r

bind r source-file ~/.config/tmux/tmux.conf
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind C-a send-prefix

set -g prefix C-a
set -g mouse on                          # enable mouse support
set -g base-index 1                      # start window numbering at 1
set -g pane-base-index 1                 # start pane numbering at 1
set -g default-terminal "${TERM}"        # use terminal from environment
set -g history-limit 50000               # increase scrollback history
set -g renumber-windows on               # renumber windows after close
set -g display-time 4000                 # message display time (ms)
set -g set-titles on                     # enable terminal window titles
set -g set-titles-string "#{pane_title}" # set title to current pane title

set -s escape-time 0                     # remove Escape key delay

RED="#ea6962"
GREEN="#a9b665"
YELLOW="#d8a657"
BLUE="#7daea3"
MAGENTA="#d3869b"
CYAN="#89b482"
LIGHT_GRAY="#3c3836"
DARK_GRAY="#32302F"
DDD="#3c3836"

HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"

set -g status-style bg=${LIGHT_GRAY}
set -g status-justify centre
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=${YELLOW}]Session: [#S]"
set -g status-right "#[fg=${YELLOW}]Hostname: #h"
set -g window-status-separator ""
set -g window-status-format " #I:#W "
set -g window-status-current-format "\
#[fg=${YELLOW},bg=default]${HALF_ROUND_OPEN}\
#[bg=${YELLOW},fg=${DARK_GRAY}]#I:#W\
#[fg=${YELLOW},bg=default]${HALF_ROUND_CLOSE}\
"
