unbind r

bind r source-file ~/.config/tmux/tmux.conf
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind C-a send-prefix

set -g prefix C-a
set -g mouse on                          # enable mouse support
set -g base-index 1                      # start window numbering at 1
set -g pane-base-index 1                 # start pane numbering at 1
set -g default-terminal "${TERM}"        # use terminal from environment
set -g history-limit 50000               # increase scrollback history
set -g renumber-windows on               # renumber windows after close
set -g display-time 4000                 # message display time (ms)
set -g set-titles on                     # enable terminal window titles
set -g set-titles-string "#{pane_title}" # set title to current pane title

set -s escape-time 0                     # remove Escape key delay

HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"
STAR_SYMBOL="#(printf '\u2737')"
ZOOM_FLAG="#{?window_zoomed_flag,${STAR_SYMBOL},}"

set -g status-style bg=brightblack
set -g status-justify absolute-centre
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=yellow]Session: [#S]  |  "
set -g status-right "#[fg=yellow]Hostname: #h"
set -g window-status-separator ""
set -g window-status-format " #I:#W${ZOOM_FLAG} "
set -g window-status-current-format "\
#[fg=yellow,bg=default bold]${HALF_ROUND_OPEN}\
#[bg=yellow,fg=black]#I:#W${ZOOM_FLAG}\
#[fg=yellow,bg=default]${HALF_ROUND_CLOSE}\
"
